import { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { GUESTS, getGuestInfo } from '../lib/constants';
import { useGuest } from '../hooks/useGuest';
import PageWrapper from '../components/layout/PageWrapper';
import Button from '../components/shared/Button';
import Card from '../components/shared/Card';

/* ─── Cat image manifest (generated by scripts/rename-cats.cjs) ─── */
import catManifest from '../assets/cats/manifest.json';

/* ─── Types ─── */
type GamePhase =
  | 'intro'
  | 'roulette'
  | 'reveal'
  | 'challenge'
  | 'hold'
  | 'voting'
  | 'result';

type RoundType = 'normal' | 'double_trouble' | 'kashish_choice' | 'nightmare' | 'sudden_death';

interface RoundResult {
  playerName: string;
  catImage: string;
  roundType: RoundType;
  votes: Record<string, number>; // voter -> score (1-5)
  averageScore: number;
}

interface GameState {
  phase: GamePhase;
  round: number;
  currentPlayer: string | null;
  currentCat: string | null;
  roundType: RoundType;
  usedCats: number[];
  usedPlayers: string[];
  results: RoundResult[];
  eliminatedIds: string[]; // for sudden death
  chaosActive: boolean;
  challengeTime: number; // seconds for memorization
}

/* ─── Helpers ─── */
const CAT_COUNT = catManifest.count;

function getRandomCat(usedCats: number[]): number {
  const available = Array.from({ length: CAT_COUNT }, (_, i) => i + 1).filter(
    (n) => !usedCats.includes(n)
  );
  if (available.length === 0) return Math.floor(Math.random() * CAT_COUNT) + 1;
  return available[Math.floor(Math.random() * available.length)];
}

function getCatImagePath(catNum: number): string {
  const file = catManifest.files[catNum - 1];
  return new URL(`../assets/cats/${file}`, import.meta.url).href;
}

function getRoundType(round: number): RoundType {
  if (round % 5 === 0) return 'nightmare';
  if (round % 3 === 0) return 'double_trouble';
  if (round === 2) return 'kashish_choice';
  return 'normal';
}

function getRoundLabel(type: RoundType): string {
  switch (type) {
    case 'double_trouble': return '⚡ Double Trouble';
    case 'kashish_choice': return '👑 Kashish\'s Choice';
    case 'nightmare': return '💀 Nightmare Mode';
    case 'sudden_death': return '🔥 Sudden Death';
    default: return '🎨 Normal Round';
  }
}

function getRoundDescription(type: RoundType): string {
  switch (type) {
    case 'double_trouble': return 'Draw with your non-dominant hand!';
    case 'kashish_choice': return 'Kashish picks who goes next!';
    case 'nightmare': return 'Only 5 seconds to memorize!';
    case 'sudden_death': return 'Lowest scorer is eliminated!';
    default: return 'Memorize the cat. Copy the cat. Become the cat.';
  }
}

/* ─── Initial State ─── */
const INITIAL_STATE: GameState = {
  phase: 'intro',
  round: 0,
  currentPlayer: null,
  currentCat: null,
  roundType: 'normal',
  usedCats: [],
  usedPlayers: [],
  results: [],
  eliminatedIds: [],
  chaosActive: false,
  challengeTime: 10,
};

/* ─── Sub-components ─── */

/* Intro Screen */
function IntroScreen({ onStart }: { onStart: () => void }) {
  return (
    <div className="cat-intro">
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
        className="text-centered"
      >
        <span className="block text-xs uppercase tracking-[0.2em] text-[var(--color-dust)] mb-3">
          The funniest game
        </span>
        <h1 className="text-4xl md:text-6xl font-light text-[var(--color-ink)] font-[family-name:var(--font-display)] mb-4">
          🐱 cat copy challenge
        </h1>
        <p className="text-centered" style={{ fontSize: '14px', color: 'var(--color-dust)', maxWidth: '448px', margin: '0 auto 48px', lineHeight: '1.7' }}>
          A cat image will flash on screen. You have seconds to memorize it.
          Then you must recreate it — by drawing, posing, or pure chaos.
          Everyone votes. The best copycat wins.
        </p>

        <div className="cat-rules-grid">
          <Card className="text-centered">
            <div className="text-2xl mb-2">👀</div>
            <p className="text-[10px] uppercase tracking-widest text-[var(--color-dust)] mb-1">Step 1</p>
            <p className="text-xs text-[var(--color-ink)]">Memorize the cat</p>
          </Card>
          <Card className="text-centered">
            <div className="text-2xl mb-2">✏️</div>
            <p className="text-[10px] uppercase tracking-widest text-[var(--color-dust)] mb-1">Step 2</p>
            <p className="text-xs text-[var(--color-ink)]">Recreate it</p>
          </Card>
          <Card className="text-centered">
            <div className="text-2xl mb-2">⭐</div>
            <p className="text-[10px] uppercase tracking-widest text-[var(--color-dust)] mb-1">Step 3</p>
            <p className="text-xs text-[var(--color-ink)]">Everyone votes</p>
          </Card>
        </div>

        <div style={{ display: 'flex', justifyContent: 'center', marginTop: '40px' }}>
          <Button variant="primary" onClick={onStart}>
            Let's Go →
          </Button>
        </div>
      </motion.div>
    </div>
  );
}

/* Roulette / Player Selection */
function RouletteScreen({
  players,
  onSelected,
  roundType,
  round,
}: {
  players: { id: string; name: string; avatar: string }[];
  onSelected: (name: string) => void;
  roundType: RoundType;
  round: number;
}) {
  const [spinning, setSpinning] = useState(true);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [selectedPlayer, setSelectedPlayer] = useState<string | null>(null);
  const intervalRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    if (!spinning) return;

    let speed = 80;
    let elapsed = 0;
    const totalDuration = 2500;

    const tick = () => {
      setCurrentIdx((prev) => (prev + 1) % players.length);
      elapsed += speed;

      if (elapsed >= totalDuration) {
        // Stop on a random player
        const finalIdx = Math.floor(Math.random() * players.length);
        setCurrentIdx(finalIdx);
        setSelectedPlayer(players[finalIdx].name);
        setSpinning(false);
        return;
      }

      // Slow down progressively
      speed = Math.min(400, speed + (elapsed / totalDuration) * 15);
      intervalRef.current = setTimeout(tick, speed);
    };

    intervalRef.current = setTimeout(tick, speed);

    return () => {
      if (intervalRef.current) clearTimeout(intervalRef.current);
    };
  }, [spinning, players]);

  const currentPlayer = players[currentIdx];

  return (
    <div className="cat-roulette" style={{ padding: '40px 0', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="text-centered"
        style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', width: '100%' }}
      >
        <div style={{ marginBottom: '24px' }}>
          <span
            className="inline-block px-4 py-1.5 rounded-full text-[10px] uppercase tracking-widest bg-[var(--color-ink)] text-[var(--color-cream)]"
            style={{
              display: 'inline-block',
              padding: '6px 16px',
              borderRadius: '9999px',
              backgroundColor: 'var(--color-ink)',
              color: 'var(--color-cream)',
              fontSize: '10px',
              fontWeight: '600',
              letterSpacing: '0.15em',
              textTransform: 'uppercase'
            }}
          >
            Round {round} · {getRoundLabel(roundType)}
          </span>
        </div>

        <p
          className="text-xs uppercase tracking-[0.2em] text-[var(--color-dust)]"
          style={{
            fontSize: '12px',
            textTransform: 'uppercase',
            letterSpacing: '0.2em',
            color: 'var(--color-dust)',
            marginBottom: '32px',
            marginTop: '0px'
          }}
        >
          {spinning ? 'Selecting player...' : 'Selected!'}
        </p>

        <motion.div
          className="cat-roulette-avatar"
          animate={spinning ? { scale: [1, 1.1, 1] } : { scale: 1 }}
          transition={{ repeat: spinning ? Infinity : 0, duration: 0.3 }}
          style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', marginTop: '12px' }}
        >
          <div
            className={`cat-avatar-ring ${spinning ? 'cat-avatar-spinning' : 'cat-avatar-selected'}`}
            style={{
              width: '120px',
              height: '120px',
              borderRadius: '50%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              boxSizing: 'border-box'
            }}
          >
            <img
              src={currentPlayer.avatar}
              alt={currentPlayer.name}
              className="w-24 h-24 rounded-full object-cover"
              style={{ width: '96px', height: '96px', borderRadius: '50%', objectFit: 'cover' }}
            />
          </div>
          <p
            className="text-2xl font-light font-[family-name:var(--font-display)] text-[var(--color-ink)]"
            style={{
              marginTop: '20px',
              fontSize: '24px',
              fontFamily: 'var(--font-display)',
              color: 'var(--color-ink)',
              textAlign: 'center'
            }}
          >
            {currentPlayer.name}
          </p>
        </motion.div>

        {selectedPlayer && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5 }}
            style={{ marginTop: '32px', display: 'flex', flexDirection: 'column', alignItems: 'center' }}
          >
            <p
              className="text-sm text-[var(--color-dust)]"
              style={{
                fontSize: '14px',
                color: 'var(--color-dust)',
                marginBottom: '20px',
                textAlign: 'center',
                maxWidth: '320px',
                lineHeight: '1.5'
              }}
            >
              {getRoundDescription(roundType)}
            </p>
            <Button variant="primary" onClick={() => onSelected(selectedPlayer)}>
              Show the Cat! 🐱
            </Button>
          </motion.div>
        )}
      </motion.div>
    </div>
  );
}

/* Cat Reveal — CHAOS MODE */
function CatRevealScreen({
  catImage,
  onDone,
  duration,
  roundType,
}: {
  catImage: string;
  onDone: () => void;
  duration: number;
  roundType: RoundType;
}) {
  const [timeLeft, setTimeLeft] = useState(duration);
  const [showCat, setShowCat] = useState(false);

  useEffect(() => {
    // Quick dramatic pause, then show
    const showTimer = setTimeout(() => setShowCat(true), 800);
    return () => clearTimeout(showTimer);
  }, []);

  useEffect(() => {
    if (!showCat) return;
    if (timeLeft <= 0) {
      onDone();
      return;
    }
    const timer = setTimeout(() => setTimeLeft((t) => t - 1), 1000);
    return () => clearTimeout(timer);
  }, [timeLeft, onDone, showCat]);

  return (
    <div className="cat-chaos-screen">
      {/* Chaos background effects */}
      <div className="cat-chaos-bg" />

      <AnimatePresence>
        {!showCat ? (
          <motion.div
            key="countdown"
            initial={{ scale: 0.5, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 2, opacity: 0 }}
            className="cat-chaos-countdown"
          >
            <span className="text-8xl">🐱</span>
            <p className="text-2xl text-white mt-4 font-[family-name:var(--font-display)]">
              Get ready...
            </p>
          </motion.div>
        ) : (
          <motion.div
            key="cat-reveal"
            initial={{ scale: 0.3, rotate: -10, opacity: 0 }}
            animate={{ scale: 1, rotate: 0, opacity: 1 }}
            transition={{ type: 'spring', damping: 12, stiffness: 200 }}
            className="cat-chaos-reveal"
          >
            {roundType === 'nightmare' && (
              <div className="cat-nightmare-overlay">💀 NIGHTMARE MODE 💀</div>
            )}

            <div className="cat-chaos-image-container">
              <img
                src={catImage}
                alt="Memorize this cat!"
                className="cat-chaos-image"
              />
            </div>

            <div className="cat-chaos-timer">
              <div className="cat-chaos-timer-ring">
                <svg viewBox="0 0 100 100" className="cat-timer-svg">
                  <circle
                    cx="50"
                    cy="50"
                    r="45"
                    fill="none"
                    stroke="rgba(255,255,255,0.2)"
                    strokeWidth="4"
                  />
                  <circle
                    cx="50"
                    cy="50"
                    r="45"
                    fill="none"
                    stroke={timeLeft <= 3 ? '#C3232B' : '#fff'}
                    strokeWidth="4"
                    strokeDasharray={`${2 * Math.PI * 45}`}
                    strokeDashoffset={`${2 * Math.PI * 45 * (1 - timeLeft / duration)}`}
                    strokeLinecap="round"
                    className="cat-timer-progress"
                  />
                </svg>
                <span className={`cat-timer-text ${timeLeft <= 3 ? 'cat-timer-danger' : ''}`}>
                  {timeLeft}
                </span>
              </div>
              <p className="text-xs uppercase tracking-widest text-white/70 mt-2">
                MEMORIZE!
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

/* Hold / Drawing Phase */
function HoldScreen({
  playerName,
  roundType,
  onDone,
}: {
  playerName: string;
  roundType: RoundType;
  onDone: () => void;
}) {
  const [timeLeft, setTimeLeft] = useState(60);

  useEffect(() => {
    if (timeLeft <= 0) {
      onDone();
      return;
    }
    const timer = setTimeout(() => setTimeLeft((t) => t - 1), 1000);
    return () => clearTimeout(timer);
  }, [timeLeft, onDone]);

  return (
    <div className="cat-hold-screen">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-centered"
      >
        <h2 className="text-3xl md:text-5xl font-light font-[family-name:var(--font-display)] text-[var(--color-ink)] mb-4">
          {playerName}'s turn
        </h2>
        <p className="text-sm text-[var(--color-dust)] mb-2">
          {roundType === 'double_trouble'
            ? '⚡ Use your non-dominant hand!'
            : 'Recreate the cat from memory!'}
        </p>
        <p className="text-xs text-[var(--color-dust)] mb-8">
          Draw it, pose for it, sculpt it — anything goes.
        </p>

        <div className="cat-hold-timer">
          <div className="cat-hold-timer-circle">
            <svg viewBox="0 0 120 120">
              <circle
                cx="60"
                cy="60"
                r="54"
                fill="none"
                stroke="var(--color-dust)"
                strokeWidth="2"
                opacity="0.3"
              />
              <circle
                cx="60"
                cy="60"
                r="54"
                fill="none"
                stroke={timeLeft <= 10 ? 'var(--color-red)' : 'var(--color-ink)'}
                strokeWidth="3"
                strokeDasharray={`${2 * Math.PI * 54}`}
                strokeDashoffset={`${2 * Math.PI * 54 * (1 - timeLeft / 60)}`}
                strokeLinecap="round"
                className="cat-timer-progress"
              />
            </svg>
            <span className={`cat-hold-timer-text ${timeLeft <= 10 ? 'text-[var(--color-red)]' : ''}`}>
              {timeLeft}s
            </span>
          </div>
        </div>

        <div style={{ display: 'flex', justifyContent: 'center', marginTop: '32px' }}>
          <Button variant="primary" onClick={onDone}>
            Done! Show Everyone →
          </Button>
        </div>
      </motion.div>
    </div>
  );
}

/* Voting Phase */
function VotingScreen({
  playerName,
  catImage,
  voters,
  onSubmitVotes,
}: {
  playerName: string;
  catImage: string;
  voters: { id: string; name: string; avatar: string }[];
  onSubmitVotes: (votes: Record<string, number>) => void;
}) {
  const [scores, setScores] = useState<Record<string, number>>({});
  const [submitted, setSubmitted] = useState(false);

  const handleScore = (voterId: string, score: number) => {
    setScores((prev) => ({ ...prev, [voterId]: score }));
  };

  const handleSubmit = () => {
    setSubmitted(true);
    onSubmitVotes(scores);
  };

  const allVoted = voters.every((v) => scores[v.id] !== undefined);

  return (
    <div className="cat-voting-screen">
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="text-centered"
      >
        <span className="block text-xs uppercase tracking-[0.2em] text-[var(--color-dust)] mb-2">
          How'd they do?
        </span>
        <h2 className="text-3xl md:text-4xl font-light font-[family-name:var(--font-display)] text-[var(--color-ink)] mb-6">
          Rate {playerName}'s copycat
        </h2>

        <div className="cat-voting-comparison">
          <div className="cat-voting-original">
            <p className="text-[10px] uppercase tracking-widest text-[var(--color-dust)] mb-2">
              Original
            </p>
            <img src={catImage} alt="Original cat" className="cat-voting-img" />
          </div>
          <div className="cat-voting-vs">
            <span className="text-2xl">⚡</span>
          </div>
          <div className="cat-voting-recreation">
            <p className="text-[10px] uppercase tracking-widest text-[var(--color-dust)] mb-2">
              Recreation
            </p>
            <div className="cat-voting-placeholder">
              <span className="text-4xl">🎨</span>
              <p className="text-[10px] text-[var(--color-dust)] mt-2">
                Look at {playerName}'s attempt!
              </p>
            </div>
          </div>
        </div>

        {!submitted ? (
          <div className="cat-voting-scores">
            <p className="text-xs text-[var(--color-dust)] mb-4">
              Each voter rates 1–5 stars
            </p>
            <div className="cat-voting-voters">
              {voters.map((voter) => (
                <div key={voter.id} className="cat-voter-row">
                  <div className="cat-voter-info">
                    <img
                      src={voter.avatar}
                      alt={voter.name}
                      className="cat-voter-avatar"
                    />
                    <span className="text-xs text-[var(--color-ink)]">
                      {voter.name}
                    </span>
                  </div>
                  <div className="cat-star-rating">
                    {[1, 2, 3, 4, 5].map((star) => (
                      <button
                        key={star}
                        onClick={() => handleScore(voter.id, star)}
                        className={`cat-star ${
                          scores[voter.id] !== undefined && scores[voter.id] >= star
                            ? 'cat-star-active'
                            : ''
                        }`}
                      >
                        ★
                      </button>
                    ))}
                  </div>
                </div>
              ))}
            </div>
            <div style={{ display: 'flex', justifyContent: 'center', marginTop: '24px' }}>
              <Button variant="primary" onClick={handleSubmit} disabled={!allVoted}>
                Submit Votes
              </Button>
            </div>
          </div>
        ) : (
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="mt-6"
          >
            <p className="text-sm text-[var(--color-dust)]">Votes recorded! ✓</p>
          </motion.div>
        )}
      </motion.div>
    </div>
  );
}

/* Result Screen */
function ResultScreen({
  result,
  catImage,
  onNextRound,
  onEndGame,
  isLastRound,
}: {
  result: RoundResult;
  catImage: string;
  onNextRound: () => void;
  onEndGame: () => void;
  isLastRound: boolean;
}) {
  const scoreEmoji =
    result.averageScore >= 4
      ? '🏆'
      : result.averageScore >= 3
        ? '👏'
        : result.averageScore >= 2
          ? '😅'
          : '💀';

  return (
    <div className="cat-result-screen">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-centered"
      >
        <span className="text-6xl block mb-4">{scoreEmoji}</span>
        <h2 className="text-3xl md:text-4xl font-light font-[family-name:var(--font-display)] text-[var(--color-ink)] mb-2">
          {result.playerName}'s Score
        </h2>
        <p className="text-5xl font-light font-[family-name:var(--font-display)] text-[var(--color-red)] mb-6">
          {result.averageScore.toFixed(1)}
          <span className="text-lg text-[var(--color-dust)]"> / 5</span>
        </p>

        <div className="cat-result-comparison">
          <img src={catImage} alt="The cat" className="cat-result-img" />
        </div>

        <div className="cat-result-breakdown">
          {Object.entries(result.votes).map(([voter, score]) => (
            <div key={voter} className="cat-result-vote">
              <span className="text-xs text-[var(--color-dust)]">{voter}</span>
              <span className="text-xs text-[var(--color-ink)]">
                {'★'.repeat(score)}
                {'☆'.repeat(5 - score)}
              </span>
            </div>
          ))}
        </div>

        <div style={{ display: 'flex', gap: '16px', justifyContent: 'center', marginTop: '32px' }}>
          {!isLastRound && (
            <Button variant="primary" onClick={onNextRound}>
              Next Round →
            </Button>
          )}
          <Button variant="ghost" onClick={onEndGame}>
            End Game
          </Button>
        </div>
      </motion.div>
    </div>
  );
}

/* Final Scoreboard */
function ScoreboardScreen({
  results,
  onPlayAgain,
}: {
  results: RoundResult[];
  onPlayAgain: () => void;
}) {
  const navigate = useNavigate();

  // Aggregate scores per player
  const playerScores = useMemo(() => {
    const scores: Record<string, { total: number; rounds: number }> = {};
    results.forEach((r) => {
      if (!scores[r.playerName]) scores[r.playerName] = { total: 0, rounds: 0 };
      scores[r.playerName].total += r.averageScore;
      scores[r.playerName].rounds += 1;
    });
    return Object.entries(scores)
      .map(([name, data]) => ({
        name,
        avg: data.total / data.rounds,
        total: data.total,
        rounds: data.rounds,
      }))
      .sort((a, b) => b.avg - a.avg);
  }, [results]);

  return (
    <div className="cat-scoreboard">
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-centered"
      >
        <span className="text-6xl block mb-4">🏆</span>
        <h2 className="text-4xl md:text-5xl font-light font-[family-name:var(--font-display)] text-[var(--color-ink)] mb-8">
          Final Scores
        </h2>

        <div className="cat-scoreboard-list">
          {playerScores.map((player, idx) => (
            <motion.div
              key={player.name}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: idx * 0.15 }}
              className={`cat-scoreboard-row ${idx === 0 ? 'cat-scoreboard-winner' : ''}`}
            >
              <div className="cat-scoreboard-rank">
                {idx === 0 ? '👑' : `#${idx + 1}`}
              </div>
              <div className="cat-scoreboard-name">{player.name}</div>
              <div className="cat-scoreboard-score">
                {player.avg.toFixed(1)}
                <span className="text-[var(--color-dust)]"> avg</span>
              </div>
            </motion.div>
          ))}
        </div>

        <div style={{ display: 'flex', gap: '16px', justifyContent: 'center', marginTop: '40px' }}>
          <Button variant="primary" onClick={onPlayAgain}>
            Play Again
          </Button>
          <Button variant="ghost" onClick={() => navigate('/games')}>
            ← Back to Games
          </Button>
        </div>
      </motion.div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════
   Main Cat Copy Challenge Component
   ═══════════════════════════════════════════════════ */

export default function CatCopyPage() {
  const navigate = useNavigate();
  const { guestName } = useGuest();
  const [gameState, setGameState] = useState<GameState>({ ...INITIAL_STATE });
  const [showScoreboard, setShowScoreboard] = useState(false);

  // Get eligible players (all guests including Kashish by default)
  const allPlayers = useMemo(() => {
    return GUESTS.map((g) => getGuestInfo(g.id));
  }, []);

  const getAvailablePlayers = useCallback(
    (roundType: RoundType, eliminatedIds: string[], usedPlayers: string[]) => {
      let pool = allPlayers.filter((p) => !eliminatedIds.includes(p.id));
      // For Kashish's Choice, exclude Kashish from being selected
      if (roundType === 'kashish_choice') {
        pool = pool.filter((p) => p.id !== 'kashish');
      }
      // Try to avoid repeat players within a game
      const unused = pool.filter((p) => !usedPlayers.includes(p.name));
      return unused.length > 0 ? unused : pool;
    },
    [allPlayers]
  );

  // Start a new game
  const handleStart = useCallback(() => {
    const round = 1;
    const roundType = getRoundType(round);
    setGameState({
      ...INITIAL_STATE,
      phase: 'roulette',
      round,
      roundType,
      challengeTime: roundType === 'nightmare' ? 5 : 10,
    });
    setShowScoreboard(false);
  }, []);

  // Player selected from roulette
  const handlePlayerSelected = useCallback(
    (playerName: string) => {
      const catNum = getRandomCat(gameState.usedCats);
      setGameState((prev) => ({
        ...prev,
        phase: 'reveal',
        currentPlayer: playerName,
        currentCat: getCatImagePath(catNum),
        usedCats: [...prev.usedCats, catNum],
        usedPlayers: [...prev.usedPlayers, playerName],
        chaosActive: true,
      }));
    },
    [gameState.usedCats]
  );

  // Cat memorization done
  const handleRevealDone = useCallback(() => {
    setGameState((prev) => ({
      ...prev,
      phase: 'hold',
      chaosActive: false,
    }));
  }, []);

  // Drawing phase done
  const handleHoldDone = useCallback(() => {
    setGameState((prev) => ({
      ...prev,
      phase: 'voting',
    }));
  }, []);

  // Votes submitted
  const handleVotesSubmitted = useCallback(
    (votes: Record<string, number>) => {
      const voteValues = Object.values(votes);
      const avg = voteValues.length > 0
        ? voteValues.reduce((a, b) => a + b, 0) / voteValues.length
        : 0;

      // Map voter IDs to names for display
      const namedVotes: Record<string, number> = {};
      Object.entries(votes).forEach(([voterId, score]) => {
        const info = getGuestInfo(voterId);
        namedVotes[info.name] = score;
      });

      const result: RoundResult = {
        playerName: gameState.currentPlayer!,
        catImage: gameState.currentCat!,
        roundType: gameState.roundType,
        votes: namedVotes,
        averageScore: avg,
      };

      setGameState((prev) => ({
        ...prev,
        phase: 'result',
        results: [...prev.results, result],
      }));
    },
    [gameState.currentPlayer, gameState.currentCat, gameState.roundType]
  );

  // Next round
  const handleNextRound = useCallback(() => {
    const nextRound = gameState.round + 1;
    const roundType = getRoundType(nextRound);

    setGameState((prev) => ({
      ...prev,
      phase: 'roulette',
      round: nextRound,
      roundType,
      currentPlayer: null,
      currentCat: null,
      chaosActive: false,
      challengeTime: roundType === 'nightmare' ? 5 : 10,
    }));
  }, [gameState.round]);

  // End game
  const handleEndGame = useCallback(() => {
    setShowScoreboard(true);
  }, []);

  // Play again
  const handlePlayAgain = useCallback(() => {
    setGameState({ ...INITIAL_STATE });
    setShowScoreboard(false);
  }, []);

  // Get voters (all players except current player)
  const currentVoters = useMemo(() => {
    return allPlayers.filter((p) => p.name !== gameState.currentPlayer);
  }, [allPlayers, gameState.currentPlayer]);

  // Available players for roulette
  const roulettePlayers = useMemo(() => {
    return getAvailablePlayers(
      gameState.roundType,
      gameState.eliminatedIds,
      gameState.usedPlayers
    );
  }, [getAvailablePlayers, gameState.roundType, gameState.eliminatedIds, gameState.usedPlayers]);

  /* ─── Render ─── */

  if (showScoreboard) {
    return (
      <PageWrapper className="bg-[var(--color-parchment)]">
        <div className="page-container">
          <ScoreboardScreen
            results={gameState.results}
            onPlayAgain={handlePlayAgain}
          />
        </div>
      </PageWrapper>
    );
  }

  // Chaos mode renders full-screen without page wrapper
  if (gameState.phase === 'reveal' && gameState.currentCat) {
    return (
      <CatRevealScreen
        catImage={gameState.currentCat}
        onDone={handleRevealDone}
        duration={gameState.challengeTime}
        roundType={gameState.roundType}
      />
    );
  }

  return (
    <PageWrapper className="bg-[var(--color-parchment)]">
      <div className="page-container cat-copy-page">
        {/* Back button (not on intro) */}
        {gameState.phase !== 'intro' && (
          <button
            onClick={() =>
              gameState.phase === 'roulette' && gameState.round === 1
                ? setGameState({ ...INITIAL_STATE })
                : navigate('/games')
            }
            className="text-xs uppercase tracking-[0.2em] mb-6 cursor-pointer text-[var(--color-dust)] hover:text-[var(--color-ink)] transition-colors"
          >
            ← Back
          </button>
        )}

        <AnimatePresence mode="wait">
          {gameState.phase === 'intro' && (
            <motion.div key="intro" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <IntroScreen onStart={handleStart} />
            </motion.div>
          )}

          {gameState.phase === 'roulette' && (
            <motion.div key="roulette" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <RouletteScreen
                players={roulettePlayers}
                onSelected={handlePlayerSelected}
                roundType={gameState.roundType}
                round={gameState.round}
              />
            </motion.div>
          )}

          {gameState.phase === 'hold' && (
            <motion.div key="hold" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <HoldScreen
                playerName={gameState.currentPlayer!}
                roundType={gameState.roundType}
                onDone={handleHoldDone}
              />
            </motion.div>
          )}

          {gameState.phase === 'voting' && (
            <motion.div key="voting" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <VotingScreen
                playerName={gameState.currentPlayer!}
                catImage={gameState.currentCat!}
                voters={currentVoters}
                onSubmitVotes={handleVotesSubmitted}
              />
            </motion.div>
          )}

          {gameState.phase === 'result' && gameState.results.length > 0 && (
            <motion.div key="result" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <ResultScreen
                result={gameState.results[gameState.results.length - 1]}
                catImage={gameState.currentCat!}
                onNextRound={handleNextRound}
                onEndGame={handleEndGame}
                isLastRound={false}
              />
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </PageWrapper>
  );
}
