import { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { GUESTS, getGuestInfo } from '../lib/constants';
import { useGuest } from '../hooks/useGuest';
import { supabase, isSupabaseConfigured } from '../lib/supabase';
import PageWrapper from '../components/layout/PageWrapper';
import Button from '../components/shared/Button';
import Card from '../components/shared/Card';

/* ─── Cat image manifest (generated by scripts/rename-cats.cjs) ─── */
import catManifest from '../assets/cats/manifest.json';

/* ─── Types ─── */
type GamePhase =
  | 'intro'
  | 'lobby'
  | 'roulette'
  | 'reveal'
  | 'challenge'
  | 'hold'
  | 'voting'
  | 'result'
  | 'scoreboard';

type RoundType = 'normal' | 'double_trouble' | 'kashish_choice' | 'nightmare' | 'sudden_death';

interface RoundResult {
  playerName: string;
  catImage: string;
  roundType: RoundType;
  votes: Record<string, number>; // voter -> score (1-5)
  averageScore: number;
}

interface GameState {
  phase: GamePhase;
  round: number;
  currentPlayer: string | null;
  currentCat: string | null;
  roundType: RoundType;
  usedCats: number[];
  usedPlayers: string[];
  results: RoundResult[];
  eliminatedIds: string[]; // for sudden death
  chaosActive: boolean;
  challengeTime: number; // seconds for memorization
}

/* ─── Helpers ─── */
const CAT_COUNT = catManifest.count;

function getRandomCat(usedCats: number[]): number {
  const available = Array.from({ length: CAT_COUNT }, (_, i) => i + 1).filter(
    (n) => !usedCats.includes(n)
  );
  if (available.length === 0) return Math.floor(Math.random() * CAT_COUNT) + 1;
  return available[Math.floor(Math.random() * available.length)];
}

function getCatImagePath(catNum: number): string {
  const file = catManifest.files[catNum - 1];
  return new URL(`../assets/cats/${file}`, import.meta.url).href;
}

function getRoundType(round: number): RoundType {
  if (round % 5 === 0) return 'nightmare';
  if (round % 3 === 0) return 'double_trouble';
  if (round === 2) return 'kashish_choice';
  return 'normal';
}

function getRoundLabel(type: RoundType): string {
  switch (type) {
    case 'double_trouble': return '⚡ Double Trouble';
    case 'kashish_choice': return '👑 Kashish\'s Choice';
    case 'nightmare': return '💀 Nightmare Mode';
    case 'sudden_death': return '🔥 Sudden Death';
    default: return '🎨 Normal Round';
  }
}

function getRoundDescription(type: RoundType): string {
  switch (type) {
    case 'double_trouble': return 'Draw with your non-dominant hand!';
    case 'kashish_choice': return 'Kashish picks who goes next!';
    case 'nightmare': return 'Only 5 seconds to memorize!';
    case 'sudden_death': return 'Lowest scorer is eliminated!';
    default: return 'Memorize the cat. Copy the cat. Become the cat.';
  }
}

/* ─── Initial State ─── */
const INITIAL_STATE: GameState = {
  phase: 'intro',
  round: 0,
  currentPlayer: null,
  currentCat: null,
  roundType: 'normal',
  usedCats: [],
  usedPlayers: [],
  results: [],
  eliminatedIds: [],
  chaosActive: false,
  challengeTime: 10,
};

/* ─── Sub-components ─── */

/* Intro Screen */
function IntroScreen({ onStart }: { onStart: () => void }) {
  return (
    <div className="cat-intro">
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
        className="text-centered"
      >
        <span className="block text-xs uppercase tracking-[0.2em] text-[var(--color-dust)] mb-3">
          The funniest game
        </span>
        <div style={{ fontSize: '48px', lineHeight: 1, marginBottom: '12px' }}>🐱</div>
        <h1 className="text-4xl md:text-6xl font-light text-[var(--color-ink)] font-[family-name:var(--font-display)] mb-4">
          cat copy challenge
        </h1>
        <p className="text-centered" style={{ fontSize: '14px', color: 'var(--color-dust)', maxWidth: '448px', margin: '0 auto 48px', lineHeight: '1.7' }}>
          A cat image will flash on screen. You have seconds to memorize it.
          Then you must recreate it — by drawing, posing, or pure chaos.
          Everyone votes. The best copycat wins.
        </p>

        <div className="cat-rules-grid">
          <Card className="text-centered">
            <div className="text-2xl mb-2">👀</div>
            <p className="text-[10px] uppercase tracking-widest text-[var(--color-dust)] mb-1">Step 1</p>
            <p className="text-xs text-[var(--color-ink)]">Memorize the cat</p>
          </Card>
          <Card className="text-centered">
            <div className="text-2xl mb-2">✏️</div>
            <p className="text-[10px] uppercase tracking-widest text-[var(--color-dust)] mb-1">Step 2</p>
            <p className="text-xs text-[var(--color-ink)]">Recreate it</p>
          </Card>
          <Card className="text-centered">
            <div className="text-2xl mb-2">⭐</div>
            <p className="text-[10px] uppercase tracking-widest text-[var(--color-dust)] mb-1">Step 3</p>
            <p className="text-xs text-[var(--color-ink)]">Everyone votes</p>
          </Card>
        </div>

        <div style={{ display: 'flex', justifyContent: 'center', marginTop: '40px' }}>
          <Button variant="primary" onClick={onStart}>
            Let's Go →
          </Button>
        </div>
      </motion.div>
    </div>
  );
}

/* Roulette / Player Selection */
function RouletteScreen({
  players,
  onSelected,
  roundType,
  round,
}: {
  players: { id: string; name: string; avatar: string }[];
  onSelected: (name: string) => void;
  roundType: RoundType;
  round: number;
}) {
  const [spinning, setSpinning] = useState(true);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [selectedPlayer, setSelectedPlayer] = useState<string | null>(null);
  const intervalRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    if (!spinning) return;

    let speed = 80;
    let elapsed = 0;
    const totalDuration = 2500;

    const tick = () => {
      setCurrentIdx((prev) => (prev + 1) % players.length);
      elapsed += speed;

      if (elapsed >= totalDuration) {
        // Stop on a random player
        const finalIdx = Math.floor(Math.random() * players.length);
        setCurrentIdx(finalIdx);
        setSelectedPlayer(players[finalIdx].name);
        setSpinning(false);
        return;
      }

      // Slow down progressively
      speed = Math.min(400, speed + (elapsed / totalDuration) * 15);
      intervalRef.current = setTimeout(tick, speed);
    };

    intervalRef.current = setTimeout(tick, speed);

    return () => {
      if (intervalRef.current) clearTimeout(intervalRef.current);
    };
  }, [spinning, players]);

  const currentPlayer = players[currentIdx];

  return (
    <div className="cat-roulette" style={{ padding: '40px 0', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="text-centered"
        style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', width: '100%' }}
      >
        <div style={{ marginBottom: '24px' }}>
          <span
            className="inline-block px-4 py-1.5 rounded-full text-[10px] uppercase tracking-widest bg-[var(--color-ink)] text-[var(--color-cream)]"
            style={{
              display: 'inline-block',
              padding: '6px 16px',
              borderRadius: '9999px',
              backgroundColor: 'var(--color-ink)',
              color: 'var(--color-cream)',
              fontSize: '10px',
              fontWeight: '600',
              letterSpacing: '0.15em',
              textTransform: 'uppercase'
            }}
          >
            Round {round} · {getRoundLabel(roundType)}
          </span>
        </div>

        <p
          className="text-xs uppercase tracking-[0.2em] text-[var(--color-dust)]"
          style={{
            fontSize: '12px',
            textTransform: 'uppercase',
            letterSpacing: '0.2em',
            color: 'var(--color-dust)',
            marginBottom: '32px',
            marginTop: '0px'
          }}
        >
          {spinning ? 'Selecting player...' : 'Selected!'}
        </p>

        <motion.div
          className="cat-roulette-avatar"
          animate={spinning ? { scale: [1, 1.1, 1] } : { scale: 1 }}
          transition={{ repeat: spinning ? Infinity : 0, duration: 0.3 }}
          style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', marginTop: '12px' }}
        >
          <div
            className={`cat-avatar-ring ${spinning ? 'cat-avatar-spinning' : 'cat-avatar-selected'}`}
            style={{
              width: '120px',
              height: '120px',
              borderRadius: '50%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              boxSizing: 'border-box'
            }}
          >
            <img
              src={currentPlayer.avatar}
              alt={currentPlayer.name}
              className="w-24 h-24 rounded-full object-cover"
              style={{ width: '96px', height: '96px', borderRadius: '50%', objectFit: 'cover' }}
            />
          </div>
          <p
            className="text-2xl font-light font-[family-name:var(--font-display)] text-[var(--color-ink)]"
            style={{
              marginTop: '20px',
              fontSize: '24px',
              fontFamily: 'var(--font-display)',
              color: 'var(--color-ink)',
              textAlign: 'center'
            }}
          >
            {currentPlayer.name}
          </p>
        </motion.div>

        {selectedPlayer && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5 }}
            style={{ marginTop: '32px', display: 'flex', flexDirection: 'column', alignItems: 'center' }}
          >
            <p
              className="text-sm text-[var(--color-dust)]"
              style={{
                fontSize: '14px',
                color: 'var(--color-dust)',
                marginBottom: '20px',
                textAlign: 'center',
                maxWidth: '320px',
                lineHeight: '1.5'
              }}
            >
              {getRoundDescription(roundType)}
            </p>
            <Button variant="primary" onClick={() => onSelected(selectedPlayer)}>
              Show the Cat! 🐱
            </Button>
          </motion.div>
        )}
      </motion.div>
    </div>
  );
}

/* Cat Reveal — CHAOS MODE */
function CatRevealScreen({
  catImage,
  onDone,
  duration,
  roundType,
}: {
  catImage: string;
  onDone: () => void;
  duration: number;
  roundType: RoundType;
}) {
  const [timeLeft, setTimeLeft] = useState(duration);
  const [showCat, setShowCat] = useState(false);

  useEffect(() => {
    // Quick dramatic pause, then show
    const showTimer = setTimeout(() => setShowCat(true), 800);
    return () => clearTimeout(showTimer);
  }, []);

  useEffect(() => {
    if (!showCat) return;
    if (timeLeft <= 0) {
      onDone();
      return;
    }
    const timer = setTimeout(() => setTimeLeft((t) => t - 1), 1000);
    return () => clearTimeout(timer);
  }, [timeLeft, onDone, showCat]);

  return (
    <div className="cat-chaos-screen">
      {/* Chaos background effects */}
      <div className="cat-chaos-bg" />

      <AnimatePresence>
        {!showCat ? (
          <motion.div
            key="countdown"
            initial={{ scale: 0.5, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 2, opacity: 0 }}
            className="cat-chaos-countdown"
          >
            <span className="text-8xl">🐱</span>
            <p className="text-2xl text-white mt-4 font-[family-name:var(--font-display)]">
              Get ready...
            </p>
          </motion.div>
        ) : (
          <motion.div
            key="cat-reveal"
            initial={{ scale: 0.3, rotate: -10, opacity: 0 }}
            animate={{ scale: 1, rotate: 0, opacity: 1 }}
            transition={{ type: 'spring', damping: 12, stiffness: 200 }}
            className="cat-chaos-reveal"
          >
            {roundType === 'nightmare' && (
              <div className="cat-nightmare-overlay">💀 NIGHTMARE MODE 💀</div>
            )}

            <div className="cat-chaos-image-container">
              <img
                src={catImage}
                alt="Memorize this cat!"
                className="cat-chaos-image"
              />
            </div>

            <div className="cat-chaos-timer">
              <div className="cat-chaos-timer-ring">
                <svg viewBox="0 0 100 100" className="cat-timer-svg">
                  <circle
                    cx="50"
                    cy="50"
                    r="45"
                    fill="none"
                    stroke="rgba(255,255,255,0.2)"
                    strokeWidth="4"
                  />
                  <circle
                    cx="50"
                    cy="50"
                    r="45"
                    fill="none"
                    stroke={timeLeft <= 3 ? '#C3232B' : '#fff'}
                    strokeWidth="4"
                    strokeDasharray={`${2 * Math.PI * 45}`}
                    strokeDashoffset={`${2 * Math.PI * 45 * (1 - timeLeft / duration)}`}
                    strokeLinecap="round"
                    className="cat-timer-progress"
                  />
                </svg>
                <span className={`cat-timer-text ${timeLeft <= 3 ? 'cat-timer-danger' : ''}`}>
                  {timeLeft}
                </span>
              </div>
              <p className="text-xs uppercase tracking-widest text-white/70 mt-2">
                MEMORIZE!
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

/* Hold / Drawing Phase */
function HoldScreen({
  playerName,
  roundType,
  onDone,
}: {
  playerName: string;
  roundType: RoundType;
  onDone: () => void;
}) {
  const [timeLeft, setTimeLeft] = useState(60);

  useEffect(() => {
    if (timeLeft <= 0) {
      onDone();
      return;
    }
    const timer = setTimeout(() => setTimeLeft((t) => t - 1), 1000);
    return () => clearTimeout(timer);
  }, [timeLeft, onDone]);

  return (
    <div className="cat-hold-screen">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-centered"
      >
        <h2 className="text-3xl md:text-5xl font-light font-[family-name:var(--font-display)] text-[var(--color-ink)] mb-4">
          {playerName}'s turn
        </h2>
        <p className="text-sm text-[var(--color-dust)] mb-2">
          {roundType === 'double_trouble'
            ? '⚡ Use your non-dominant hand!'
            : 'Recreate the cat from memory!'}
        </p>
        <p className="text-xs text-[var(--color-dust)] mb-8">
          Draw it, pose for it, sculpt it — anything goes.
        </p>

        <div className="cat-hold-timer">
          <div className="cat-hold-timer-circle">
            <svg viewBox="0 0 120 120">
              <circle
                cx="60"
                cy="60"
                r="54"
                fill="none"
                stroke="var(--color-dust)"
                strokeWidth="2"
                opacity="0.3"
              />
              <circle
                cx="60"
                cy="60"
                r="54"
                fill="none"
                stroke={timeLeft <= 10 ? 'var(--color-red)' : 'var(--color-ink)'}
                strokeWidth="3"
                strokeDasharray={`${2 * Math.PI * 54}`}
                strokeDashoffset={`${2 * Math.PI * 54 * (1 - timeLeft / 60)}`}
                strokeLinecap="round"
                className="cat-timer-progress"
              />
            </svg>
            <span className={`cat-hold-timer-text ${timeLeft <= 10 ? 'text-[var(--color-red)]' : ''}`}>
              {timeLeft}s
            </span>
          </div>
        </div>

        <div style={{ display: 'flex', justifyContent: 'center', marginTop: '32px' }}>
          <Button variant="primary" onClick={onDone}>
            Done! Show Everyone →
          </Button>
        </div>
      </motion.div>
    </div>
  );
}

/* Voting Phase */
interface VoteItem {
  voter_name: string;
  score: number;
}

function getPlayerPresence(player: { is_connected?: boolean; last_seen?: string }) {
  if (player.is_connected) {
    return { label: 'connected', color: '#10B981', emoji: '🟢' };
  }
  const lastSeenTime = player.last_seen ? new Date(player.last_seen).getTime() : 0;
  const secondsAgo = (Date.now() - lastSeenTime) / 1000;
  
  if (secondsAgo < 45) {
    return { label: 'reconnecting', color: '#FBBF24', emoji: '🟡' };
  }
  return { label: 'away', color: '#9CA3AF', emoji: '⚪' };
}

function VotingScreen({
  playerName,
  catImage,
  voters,
  votesList,
  onSubmitVote,
  guestName,
  joinedPlayers,
}: {
  playerName: string;
  catImage: string;
  voters: { id: string; name: string; avatar: string }[];
  votesList: VoteItem[];
  onSubmitVote: (score: number) => void;
  guestName: string;
  joinedPlayers: { player_name: string; is_host: boolean; is_connected?: boolean; last_seen?: string }[];
}) {
  const [selectedScore, setSelectedScore] = useState<number | null>(null);
  const [submitted, setSubmitted] = useState(false);

  const isCurrentPlayer = playerName === guestName;
  const hasVoted = votesList.some((v) => v.voter_name === guestName);

  const handleSubmit = () => {
    if (selectedScore !== null) {
      onSubmitVote(selectedScore);
      setSubmitted(true);
    }
  };

  return (
    <div className="cat-voting-screen">
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="text-centered"
      >
        <span className="block text-xs uppercase tracking-[0.2em] text-[var(--color-dust)] mb-2">
          {isCurrentPlayer ? 'They are rating you!' : "How'd they do?"}
        </span>
        <h2 className="text-3xl md:text-4xl font-light font-[family-name:var(--font-display)] text-[var(--color-ink)] mb-6 text-centered">
          {isCurrentPlayer ? "Waiting for players to rate your copycat" : `Rate ${playerName}'s copycat`}
        </h2>

        <div className="cat-voting-comparison" style={{ display: 'flex', gap: '24px', justifyContent: 'center', marginBottom: '32px', flexWrap: 'wrap' }}>
          <div className="cat-voting-original" style={{ flex: '1', minWidth: '160px', maxWidth: '240px' }}>
            <p className="text-[10px] uppercase tracking-widest text-[var(--color-dust)] mb-2">
              Original Cat
            </p>
            <img src={catImage} alt="Original cat" className="cat-voting-img" style={{ width: '100%', height: 'auto', borderRadius: '8px' }} />
          </div>
          <div className="cat-voting-recreation" style={{ flex: '1', minWidth: '160px', maxWidth: '240px' }}>
            <p className="text-[10px] uppercase tracking-widest text-[var(--color-dust)] mb-2">
              Recreation
            </p>
            <div className="cat-voting-placeholder" style={{ padding: '24px', minHeight: '160px', boxSizing: 'border-box' }}>
              <span className="text-4xl">🎨</span>
              <p className="text-[10px] text-[var(--color-dust)] mt-2">
                Look at {playerName}'s attempt!
              </p>
            </div>
          </div>
        </div>

        {isCurrentPlayer ? (
          <div className="cat-voting-scores" style={{ maxWidth: '400px', margin: '0 auto' }}>
            <p className="text-xs uppercase tracking-widest text-[var(--color-dust)] mb-4">Voter Status</p>
            <div className="cat-voting-voters" style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
              {voters.map((voter) => {
                const voted = votesList.some((v) => v.voter_name === voter.name);
                const playerPresence = joinedPlayers.find((p) => p.player_name === voter.name);
                const presence = playerPresence ? getPlayerPresence(playerPresence) : { emoji: '🟢', label: 'connected', color: '#10B981' };

                return (
                  <div key={voter.id} className="cat-voter-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px', background: 'var(--color-cream)', border: '1px solid var(--color-dust)', borderRadius: '4px' }}>
                    <div className="cat-voter-info" style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                      <img src={voter.avatar} alt={voter.name} className="cat-voter-avatar" style={{ width: '32px', height: '32px', borderRadius: '50%' }} />
                      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}>
                        <span className="text-xs text-[var(--color-ink)] font-semibold">{voter.name}</span>
                        <span style={{ fontSize: '8px', color: presence.color, textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: '2px' }}>
                          <span>{presence.emoji}</span>
                          <span>{presence.label}</span>
                        </span>
                      </div>
                    </div>
                    <span className="text-xs font-semibold" style={{ color: voted ? 'var(--color-red)' : 'var(--color-dust)' }}>
                      {voted ? 'Voted ✓' : 'Voting...'}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        ) : submitted || hasVoted ? (
          <div style={{ marginTop: '24px' }}>
            <p className="text-sm text-[var(--color-dust)]">
              Your rating of {selectedScore || votesList.find((v) => v.voter_name === guestName)?.score} stars has been recorded! ✓
            </p>
          </div>
        ) : (
          <div className="cat-voting-scores" style={{ maxWidth: '400px', margin: '0 auto' }}>
            <p className="text-xs text-[var(--color-dust)] mb-6">Rate 1–5 stars based on their copycat drawing or pose</p>
            <div className="cat-star-rating" style={{ display: 'flex', justifyContent: 'center', gap: '12px', marginBottom: '24px' }}>
              {[1, 2, 3, 4, 5].map((star) => (
                <button
                  key={star}
                  onClick={() => setSelectedScore(star)}
                  style={{
                    fontSize: '32px',
                    background: 'none',
                    border: 'none',
                    cursor: 'pointer',
                    color: (selectedScore !== null && selectedScore >= star) ? 'var(--color-crimson)' : 'var(--color-dust)',
                    transition: 'color 0.15s ease'
                  }}
                >
                  ★
                </button>
              ))}
            </div>
            <div style={{ display: 'flex', justifyContent: 'center', marginTop: '24px' }}>
              <Button variant="primary" onClick={handleSubmit} disabled={selectedScore === null}>
                Submit Rating
              </Button>
            </div>
          </div>
        )}
      </motion.div>
    </div>
  );
}



/* Result Screen */
function ResultScreen({
  result,
  catImage,
  onNextRound,
  onEndGame,
  isLastRound,
}: {
  result: RoundResult;
  catImage: string;
  onNextRound: () => void;
  onEndGame: () => void;
  isLastRound: boolean;
}) {
  const scoreEmoji =
    result.averageScore >= 4
      ? '🏆'
      : result.averageScore >= 3
        ? '👏'
        : result.averageScore >= 2
          ? '😅'
          : '💀';

  return (
    <div className="cat-result-screen">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-centered"
      >
        <span className="text-6xl block mb-4">{scoreEmoji}</span>
        <h2 className="text-3xl md:text-4xl font-light font-[family-name:var(--font-display)] text-[var(--color-ink)] mb-2">
          {result.playerName}'s Score
        </h2>
        <p className="text-5xl font-light font-[family-name:var(--font-display)] text-[var(--color-red)] mb-6">
          {result.averageScore.toFixed(1)}
          <span className="text-lg text-[var(--color-dust)]"> / 5</span>
        </p>

        <div className="cat-result-comparison">
          <img src={catImage} alt="The cat" className="cat-result-img" />
        </div>

        <div className="cat-result-breakdown">
          {Object.entries(result.votes).map(([voter, score]) => (
            <div key={voter} className="cat-result-vote">
              <span className="text-xs text-[var(--color-dust)]">{voter}</span>
              <span className="text-xs text-[var(--color-ink)]">
                {'★'.repeat(score)}
                {'☆'.repeat(5 - score)}
              </span>
            </div>
          ))}
        </div>

        <div style={{ display: 'flex', gap: '16px', justifyContent: 'center', marginTop: '32px' }}>
          {!isLastRound && (
            <Button variant="primary" onClick={onNextRound}>
              Next Round →
            </Button>
          )}
          <Button variant="ghost" onClick={onEndGame}>
            End Game
          </Button>
        </div>
      </motion.div>
    </div>
  );
}

/* Final Scoreboard */
interface AllVotesItem {
  round: number;
  voter_name: string;
  target_name: string;
  score: number;
}

function ScoreboardScreen({
  votes,
  onPlayAgain,
  isHost,
}: {
  votes: AllVotesItem[];
  onPlayAgain: () => void;
  isHost: boolean;
}) {
  const navigate = useNavigate();

  // Aggregate scores per player
  const playerScores = useMemo(() => {
    const ratings: Record<string, { sum: number; count: number }> = {};
    votes.forEach((v) => {
      const name = v.target_name;
      if (!ratings[name]) {
        ratings[name] = { sum: 0, count: 0 };
      }
      ratings[name].sum += v.score;
      ratings[name].count += 1;
    });

    return Object.entries(ratings)
      .map(([name, data]) => ({
        name,
        avg: data.count > 0 ? data.sum / data.count : 0,
        rounds: data.count,
      }))
      .sort((a, b) => b.avg - a.avg);
  }, [votes]);

  return (
    <div className="cat-scoreboard">
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-centered"
      >
        <span className="text-6xl block mb-4">🏆</span>
        <h2 className="text-4xl md:text-5xl font-light font-[family-name:var(--font-display)] text-[var(--color-ink)] mb-8">
          Final Scores
        </h2>

        <div className="cat-scoreboard-list">
          {playerScores.length > 0 ? (
            playerScores.map((player, idx) => (
              <motion.div
                key={player.name}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: idx * 0.15 }}
                className={`cat-scoreboard-row ${idx === 0 ? 'cat-scoreboard-winner' : ''}`}
              >
                <div className="cat-scoreboard-rank">
                  {idx === 0 ? '👑' : `#${idx + 1}`}
                </div>
                <div className="cat-scoreboard-name">{player.name}</div>
                <div className="cat-scoreboard-score">
                  {player.avg.toFixed(1)}
                  <span className="text-[var(--color-dust)]"> avg</span>
                </div>
              </motion.div>
            ))
          ) : (
            <p className="text-sm text-[var(--color-dust)]">No scores recorded yet!</p>
          )}
        </div>

        <div style={{ display: 'flex', gap: '16px', justifyContent: 'center', marginTop: '40px' }}>
          {isHost && (
            <Button variant="primary" onClick={onPlayAgain}>
              Play Again
            </Button>
          )}
          <Button variant="ghost" onClick={() => navigate('/games')}>
            ← Back to Games
          </Button>
        </div>
      </motion.div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════
   Main Cat Copy Challenge Component
   ═══════════════════════════════════════════════════ */

export default function CatCopyPage() {
  const navigate = useNavigate();
  const { guestName, setShowRegistration } = useGuest();
  const [gameState, setGameState] = useState<GameState>({ ...INITIAL_STATE });
  const [showScoreboard, setShowScoreboard] = useState(false);

  const GLOBAL_GAME_ID = '00000000-0000-0000-0000-000000000000';

  // Multiplayer realtime states
  const [gameId, setGameId] = useState<string | null>(GLOBAL_GAME_ID);
  const [joinedPlayers, setJoinedPlayers] = useState<{
    player_name: string;
    is_host: boolean;
    is_connected?: boolean;
    last_seen?: string;
    joined_at?: string;
  }[]>([]);
  const [votesList, setVotesList] = useState<VoteItem[]>([]);
  const [allVotesForGame, setAllVotesForGame] = useState<AllVotesItem[]>([]);
  const [isSearching, setIsSearching] = useState(true);
  const [isRejoining, setIsRejoining] = useState(false);
  const [rejoiningName, setRejoiningName] = useState('');

  const isHost = useMemo(() => {
    if (!guestName || joinedPlayers.length === 0) return false;
    const self = joinedPlayers.find((p) => p.player_name === guestName);
    return self ? self.is_host : false;
  }, [joinedPlayers, guestName]);

  // Get eligible players from the joined player list
  const activePlayers = useMemo(() => {
    if (joinedPlayers.length === 0) {
      return GUESTS.map((g) => getGuestInfo(g.id));
    }
    return joinedPlayers.map((p) => getGuestInfo(p.player_name));
  }, [joinedPlayers]);

  const getAvailablePlayers = useCallback(
    (roundType: RoundType, eliminatedIds: string[], usedPlayers: string[]) => {
      let pool = activePlayers.filter((p) => !eliminatedIds.includes(p.id));
      // For Kashish's Choice, exclude Kashish from being selected
      if (roundType === 'kashish_choice') {
        pool = pool.filter((p) => p.id !== 'kashish');
      }
      // Try to avoid repeat players within a game
      const unused = pool.filter((p) => !usedPlayers.includes(p.name));
      return unused.length > 0 ? unused : pool;
    },
    [activePlayers]
  );

  // Host handover detection & execution
  const evaluateHostStatus = useCallback(async (players: { player_name: string; is_host: boolean; is_connected?: boolean; last_seen?: string; joined_at?: string }[]) => {
    if (!GLOBAL_GAME_ID || !guestName || players.length === 0) return;

    const currentHost = players.find(p => p.is_host);

    let hostNeedsReplacement = false;
    if (!currentHost) {
      hostNeedsReplacement = true;
    } else {
      const lastSeenTime = currentHost.last_seen ? new Date(currentHost.last_seen).getTime() : 0;
      const secondsAgo = (Date.now() - lastSeenTime) / 1000;
      if (!currentHost.is_connected && secondsAgo > 120) {
        hostNeedsReplacement = true;
      }
    }

    if (hostNeedsReplacement) {
      const activeConnectedPlayers = players.filter(p => {
        const presence = getPlayerPresence(p);
        return presence.label === 'connected';
      });

      if (activeConnectedPlayers.length > 0) {
        // Sort alphabetically to be deterministic across all clients
        activeConnectedPlayers.sort((a, b) => a.player_name.localeCompare(b.player_name));
        const newHostCandidate = activeConnectedPlayers[0];

        if (newHostCandidate.player_name === guestName) {
          console.log(`Host handover: transferring host to ${guestName}`);
          
          await supabase
            .from('cat_players')
            .update({ is_host: false })
            .eq('game_id', GLOBAL_GAME_ID);

          await supabase
            .from('cat_players')
            .update({ is_host: true })
            .eq('game_id', GLOBAL_GAME_ID)
            .eq('player_name', guestName);
        }
      }
    }
  }, [guestName]);

  // Helper functions to fetch lists
  const fetchPlayersList = useCallback(async () => {
    if (!GLOBAL_GAME_ID) return;
    const { data, error } = await supabase
      .from('cat_players')
      .select('player_name, is_host, is_connected, last_seen, joined_at')
      .eq('game_id', GLOBAL_GAME_ID);
    if (error) {
      console.error('Error fetching players list:', error);
    }
    if (data) {
      const typedData = data as { player_name: string; is_host: boolean; is_connected?: boolean; last_seen?: string; joined_at?: string }[];
      setJoinedPlayers(typedData);
      evaluateHostStatus(typedData);
    }
  }, [evaluateHostStatus]);

  const fetchVotesList = useCallback(async (currentRound: number) => {
    if (!GLOBAL_GAME_ID) return;
    const { data, error } = await supabase
      .from('cat_votes')
      .select('voter_name, score')
      .eq('game_id', GLOBAL_GAME_ID)
      .eq('round', currentRound);
    if (error) {
      console.error('Error fetching votes list:', error);
    }
    if (data) {
      setVotesList(data);
    }
  }, []);

  const initializeGlobalGame = useCallback(async () => {
    if (!guestName) return;

    const { data: existingGame, error } = await supabase
      .from('cat_game')
      .select('*')
      .eq('id', GLOBAL_GAME_ID)
      .limit(1);

    if (error) {
      console.error('Error fetching global cat game:', error);
      return;
    }

    let activeGame;
    if (!existingGame || existingGame.length === 0) {
      const { data: newGame, error: insertError } = await supabase
        .from('cat_game')
        .insert([{
          id: GLOBAL_GAME_ID,
          status: 'intro',
          round: 0,
          round_type: 'normal',
          used_cats: [],
          used_players: [],
        }])
        .select()
        .single();

      if (insertError) {
        console.error('Error creating global cat game:', insertError);
        return;
      }
      activeGame = newGame;
    } else {
      activeGame = existingGame[0];
    }

    setGameId(GLOBAL_GAME_ID);

    // Database-first check: see if current guestName is already in players list
    const { data: existingPlayer } = await supabase
      .from('cat_players')
      .select('*')
      .eq('game_id', GLOBAL_GAME_ID)
      .eq('player_name', guestName)
      .limit(1);

    const playerExistsInDB = existingPlayer && existingPlayer.length > 0;

    if (playerExistsInDB) {
      console.log("Player already exists, reconnecting");
      console.log("Found existing player");
      console.log("Restoring session");
      console.log("Rejoining room");

      setIsRejoining(true);
      setRejoiningName(guestName);

      // Save/restore session locally in localStorage
      localStorage.setItem(
        'cat_session',
        JSON.stringify({
          gameId: GLOBAL_GAME_ID,
          playerName: guestName
        })
      );

      // Restore presence in DB
      await supabase
        .from('cat_players')
        .update({
          is_connected: true,
          last_seen: new Date().toISOString(),
          updated_at: new Date().toISOString()
        })
        .eq('game_id', GLOBAL_GAME_ID)
        .eq('player_name', guestName);

      await fetchPlayersList();

      setGameState({
        phase: activeGame.status as GamePhase,
        round: activeGame.round,
        currentPlayer: activeGame.current_player,
        currentCat: activeGame.current_cat,
        roundType: (activeGame.round_type || 'normal') as RoundType,
        usedCats: activeGame.used_cats || [],
        usedPlayers: activeGame.used_players || [],
        results: [],
        eliminatedIds: [],
        chaosActive: activeGame.status === 'reveal',
        challengeTime: activeGame.round_type === 'nightmare' ? 5 : 10,
      });

      setTimeout(() => {
        setIsRejoining(false);
      }, 1500);
    } else {
      // Player does not exist in DB
      localStorage.removeItem('cat_session');

      // Fetch players list first to determine initial states
      const { data: players } = await supabase
        .from('cat_players')
        .select('player_name, is_host, is_connected, last_seen, joined_at')
        .eq('game_id', GLOBAL_GAME_ID);
      
      if (players) {
        const typedData = players as { player_name: string; is_host: boolean; is_connected?: boolean; last_seen?: string; joined_at?: string }[];
        setJoinedPlayers(typedData);
        evaluateHostStatus(typedData);
      }

      if (activeGame.status !== 'intro') {
        setGameState({
          phase: activeGame.status as GamePhase,
          round: activeGame.round,
          currentPlayer: activeGame.current_player,
          currentCat: activeGame.current_cat,
          roundType: (activeGame.round_type || 'normal') as RoundType,
          usedCats: activeGame.used_cats || [],
          usedPlayers: activeGame.used_players || [],
          results: [],
          eliminatedIds: [],
          chaosActive: activeGame.status === 'reveal',
          challengeTime: activeGame.round_type === 'nightmare' ? 5 : 10,
        });
      }
    }
  }, [guestName, fetchPlayersList, evaluateHostStatus]);

  const updateHeartbeat = useCallback(async (connected: boolean = true) => {
    if (!GLOBAL_GAME_ID || !guestName) return;
    try {
      await supabase
        .from('cat_players')
        .update({
          last_seen: new Date().toISOString(),
          is_connected: connected,
          updated_at: new Date().toISOString()
        })
        .eq('game_id', GLOBAL_GAME_ID)
        .eq('player_name', guestName);
    } catch (err) {
      console.error('Error sending heartbeat:', err);
    }
  }, [guestName]);

  // Heartbeat loop and visibility state changes listener
  useEffect(() => {
    if (!gameId || !guestName) return;

    // Initial heartbeat
    updateHeartbeat(true);

    const heartbeatInterval = setInterval(() => {
      updateHeartbeat(true);
    }, 20000);

    const handleBeforeUnload = () => {
      // Use keepalive fetch to ensure the disconnect update goes through when browser closes
      const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
      const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';
      if (supabaseUrl && supabaseKey) {
        const url = `${supabaseUrl}/rest/v1/cat_players?game_id=eq.${gameId}&player_name=eq.${encodeURIComponent(guestName)}`;
        fetch(url, {
          method: 'PATCH',
          headers: {
            'Content-Type': 'application/json',
            'apikey': supabaseKey,
            'Authorization': `Bearer ${supabaseKey}`
          },
          body: JSON.stringify({ is_connected: false, last_seen: new Date().toISOString() }),
          keepalive: true
        }).catch(err => console.error('Keepalive disconnect fetch failed:', err));
      }
      updateHeartbeat(false);
    };

    const handleVisibilityChange = () => {
      if (document.visibilityState === 'hidden') {
        updateHeartbeat(false);
      } else {
        updateHeartbeat(true);
      }
    };

    window.addEventListener('beforeunload', handleBeforeUnload);
    window.addEventListener('pagehide', handleBeforeUnload);
    document.addEventListener('visibilitychange', handleVisibilityChange);

    return () => {
      clearInterval(heartbeatInterval);
      window.removeEventListener('beforeunload', handleBeforeUnload);
      window.removeEventListener('pagehide', handleBeforeUnload);
      document.removeEventListener('visibilitychange', handleVisibilityChange);
      updateHeartbeat(false);
    };
  }, [gameId, guestName, updateHeartbeat]);

  const handleJoinLobby = async () => {
    console.log("handleJoinLobby clicked! guestName:", guestName, "gameId:", gameId);
    if (!guestName) {
      console.log("guestName is missing, opening registration prompt...");
      setShowRegistration(true);
      return;
    }
    if (!gameId) {
      console.error("gameId is missing");
      return;
    }

    try {
      // Check if player already exists in the lobby/game
      const { data: existingPlayer, error: selectError } = await supabase
        .from('cat_players')
        .select('*')
        .eq('game_id', gameId)
        .eq('player_name', guestName)
        .limit(1);

      if (selectError) {
        console.error("Error checking existing player:", selectError);
      }

      const playerExists = existingPlayer && existingPlayer.length > 0;

      if (playerExists) {
        console.log("Player already exists, reconnecting");
        console.log("Found existing player");
        console.log("Restoring session");
        console.log("Rejoining room");

        // Mark the player connected and update heartbeat
        const { error: updateError } = await supabase
          .from('cat_players')
          .update({
            is_connected: true,
            last_seen: new Date().toISOString(),
            updated_at: new Date().toISOString()
          })
          .eq('game_id', gameId)
          .eq('player_name', guestName);

        if (updateError) {
          console.error("Error updating connection status:", updateError);
        }
      } else {
        // Find if any host exists
        const { data: hosts, error: hostError } = await supabase
          .from('cat_players')
          .select('player_name')
          .eq('game_id', gameId)
          .eq('is_host', true);
        
        if (hostError) {
          console.error("Error checking host existence:", hostError);
        }
        
        const hasHost = hosts && hosts.length > 0;

        const { error: insertError } = await supabase.from('cat_players').insert([{
          game_id: gameId,
          player_name: guestName,
          is_host: !hasHost,
        }]);
        if (insertError) {
          console.error('Error joining cat players list:', insertError);
        }
      }

      // Save/restore session locally
      localStorage.setItem(
        'cat_session',
        JSON.stringify({
          gameId: gameId,
          playerName: guestName
        })
      );

      // Instantly refetch players list locally so the current user sees themselves in the list
      await fetchPlayersList();

      // Check current state in DB and open waiting room if status is currently intro/scoreboard
      const { data: currentGame, error: gameError } = await supabase
        .from('cat_game')
        .select('status')
        .eq('id', gameId)
        .single();

      if (gameError) {
        console.error("Error checking current game state:", gameError);
      }

      if (currentGame) {
        if (currentGame.status === 'intro' || currentGame.status === 'scoreboard') {
          const { error: statusError } = await supabase
            .from('cat_game')
            .update({ status: 'lobby' })
            .eq('id', gameId);
          if (statusError) {
            console.error("Error updating game status to lobby:", statusError);
          }
        } else {
          // Restore their game state phase directly to the current game's status!
          setGameState((prev) => ({
            ...prev,
            phase: currentGame.status as GamePhase,
          }));
        }
      }
    } catch (err) {
      console.error("Unhandled exception in handleJoinLobby:", err);
    }
  };

  // Run discovery/initialization on load
  useEffect(() => {
    const searchTimer = setTimeout(() => {
      setIsSearching(false);
    }, 1500);

    initializeGlobalGame().finally(() => {
      setIsSearching(false);
      clearTimeout(searchTimer);
    });
  }, [initializeGlobalGame]);

  // Realtime subscription setup
  useEffect(() => {
    if (!gameId) return;

    fetchPlayersList();

    if (gameState.round > 0) {
      fetchVotesList(gameState.round);
    }

    const gameChannel = supabase
      .channel(`cat_game:${gameId}`)
      .on(
        'postgres_changes',
        { event: 'UPDATE', schema: 'public', table: 'cat_game', filter: `id=eq.${gameId}` },
        (payload: any) => {
          const newGame = payload.new;
          setGameState((prev) => ({
            ...prev,
            phase: newGame.status as GamePhase,
            round: newGame.round,
            currentPlayer: newGame.current_player,
            currentCat: newGame.current_cat,
            roundType: (newGame.round_type || 'normal') as RoundType,
            usedCats: newGame.used_cats || [],
            usedPlayers: newGame.used_players || [],
            chaosActive: newGame.status === 'reveal',
            challengeTime: newGame.round_type === 'nightmare' ? 5 : 10,
          }));
        }
      )
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'cat_players', filter: `game_id=eq.${gameId}` },
        () => {
          fetchPlayersList();
        }
      )
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'cat_votes', filter: `game_id=eq.${gameId}` },
        () => {
          if (gameState.round > 0) {
            fetchVotesList(gameState.round);
          }
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(gameChannel);
    };
  }, [gameId, gameState.round, fetchPlayersList, fetchVotesList]);

  // Fetch final votes list for scoreboard display
  const fetchAllVotesForGame = useCallback(async () => {
    if (!gameId) return;
    const { data } = await supabase
      .from('cat_votes')
      .select('round, voter_name, target_name, score')
      .eq('game_id', gameId);
    if (data) {
      setAllVotesForGame(data);
    }
  }, [gameId]);

  useEffect(() => {
    if (showScoreboard || gameState.phase === 'scoreboard') {
      fetchAllVotesForGame();
    }
  }, [showScoreboard, gameState.phase, fetchAllVotesForGame]);

  // Start game triggers roulette
  const handleStart = useCallback(async () => {
    if (!gameId) return;

    const round = 1;
    const roundType = getRoundType(round);

    await supabase
      .from('cat_game')
      .update({
        status: 'roulette',
        round,
        round_type: roundType,
        current_player: null,
        current_cat: null,
        used_cats: [],
        used_players: [],
      })
      .eq('id', gameId);
  }, [gameId]);

  // Player selected from roulette
  const handlePlayerSelected = useCallback(
    async (playerName: string) => {
      if (!gameId) return;

      const catNum = getRandomCat(gameState.usedCats);
      const catPath = getCatImagePath(catNum);

      await supabase
        .from('cat_game')
        .update({
          status: 'reveal',
          current_player: playerName,
          current_cat: catPath,
          used_cats: [...gameState.usedCats, catNum],
          used_players: [...gameState.usedPlayers, playerName],
        })
        .eq('id', gameId);
    },
    [gameId, gameState.usedCats, gameState.usedPlayers]
  );

  // Cat memorization countdown finishes
  const handleRevealDone = useCallback(async () => {
    if (!gameId) return;
    await supabase
      .from('cat_game')
      .update({ status: 'hold' })
      .eq('id', gameId);
  }, [gameId]);

  // Drawing phase finishes
  const handleHoldDone = useCallback(async () => {
    if (!gameId) return;
    await supabase
      .from('cat_game')
      .update({ status: 'voting' })
      .eq('id', gameId);
  }, [gameId]);

  const handleVotesSubmitted = useCallback(
    async (score: number) => {
      if (!gameId || !guestName || !gameState.currentPlayer) return;

      const { error } = await supabase
        .from('cat_votes')
        .insert([{
          game_id: gameId,
          round: gameState.round,
          voter_name: guestName,
          target_name: gameState.currentPlayer,
          score: score,
        }]);

      if (error) {
        console.error('Error submitting vote rating:', error);
      } else {
        // Refetch votes list locally so current guest's screen updates instantly
        fetchVotesList(gameState.round);
      }
    },
    [gameId, gameState.round, guestName, gameState.currentPlayer, fetchVotesList]
  );

  // Host reveals round results
  const handleRevealResults = useCallback(async () => {
    if (!gameId) return;

    await supabase
      .from('cat_game')
      .update({ status: 'result' })
      .eq('id', gameId);
  }, [gameId]);

  // Host transitions to next round
  const handleNextRound = useCallback(async () => {
    if (!gameId) return;

    const nextRound = gameState.round + 1;
    const roundType = getRoundType(nextRound);

    await supabase
      .from('cat_game')
      .update({
        status: 'roulette',
        round: nextRound,
        round_type: roundType,
        current_player: null,
        current_cat: null,
      })
      .eq('id', gameId);
  }, [gameId, gameState.round]);

  // Host ends game
  const handleEndGame = useCallback(async () => {
    if (!gameId) return;

    await supabase
      .from('cat_game')
      .update({ status: 'scoreboard' })
      .eq('id', gameId);
  }, [gameId]);

  // Reset game session completely
  const handlePlayAgain = useCallback(async () => {
    if (!gameId) return;

    await supabase.from('cat_votes').delete().eq('game_id', gameId);

    await supabase
      .from('cat_game')
      .update({
        status: 'lobby',
        round: 0,
        current_player: null,
        current_cat: null,
        used_cats: [],
        used_players: [],
      })
      .eq('id', gameId);

    setShowScoreboard(false);
  }, [gameId]);

  // Get voters (all players except current player)
  const currentVoters = useMemo(() => {
    return activePlayers.filter((p) => p.name !== gameState.currentPlayer);
  }, [activePlayers, gameState.currentPlayer]);

  // Available players for roulette
  const roulettePlayers = useMemo(() => {
    return getAvailablePlayers(
      gameState.roundType,
      gameState.eliminatedIds,
      gameState.usedPlayers
    );
  }, [getAvailablePlayers, gameState.roundType, gameState.eliminatedIds, gameState.usedPlayers]);

  // Compute round result dynamically from the current round's votes list
  const currentRoundResult = useMemo((): RoundResult | null => {
    if (votesList.length === 0 && gameState.currentPlayer === null) return null;

    const total = votesList.reduce((acc, curr) => acc + curr.score, 0);
    const avg = votesList.length > 0 ? total / votesList.length : 0;

    const mappedVotes: Record<string, number> = {};
    votesList.forEach((v) => {
      mappedVotes[v.voter_name] = v.score;
    });

    return {
      playerName: gameState.currentPlayer || 'Active Player',
      catImage: gameState.currentCat || '',
      roundType: gameState.roundType,
      votes: mappedVotes,
      averageScore: avg,
    };
  }, [votesList, gameState.currentPlayer, gameState.currentCat, gameState.roundType]);

  /* ─── Render ─── */

  if (isRejoining) {
    return (
      <PageWrapper className="bg-[var(--color-parchment)]">
        <div className="page-container cat-copy-page flex flex-col items-center justify-center min-h-[60vh]">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="text-centered"
          >
            <div style={{ fontSize: '64px', marginBottom: '20px' }}>🐱✨</div>
            <h1 className="text-3xl md:text-5xl font-light text-[var(--color-ink)] font-[family-name:var(--font-display)] mb-4">
              Welcome back, {rejoiningName}
            </h1>
            <p className="text-sm text-[var(--color-dust)] animate-pulse">
              Rejoining game session...
            </p>
          </motion.div>
        </div>
      </PageWrapper>
    );
  }

  if (!gameId) {
    return (
      <PageWrapper className="bg-[var(--color-parchment)]">
        <div className="page-container cat-copy-page">
          <button
            onClick={() => {
              localStorage.removeItem('cat_session');
              navigate('/games');
            }}
            className="game-back-link"
          >
            ← Back to Games
          </button>

          <div className="cat-intro">
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="text-centered"
            >
              <span className="block text-xs uppercase tracking-[0.2em] text-[var(--color-dust)] mb-3">
                Real-Time Party Game
              </span>
              <div style={{ fontSize: '48px', lineHeight: 1, marginBottom: '12px' }}>🐱</div>
              <h1 className="text-4xl md:text-6xl font-light text-[var(--color-ink)] font-[family-name:var(--font-display)] mb-4">
                cat copy challenge
              </h1>
              <p className="text-centered" style={{ fontSize: '14px', color: 'var(--color-dust)', maxWidth: '448px', margin: '0 auto 48px', lineHeight: '1.7' }}>
                Connecting to global game session...
              </p>
            </motion.div>
          </div>
        </div>
      </PageWrapper>
    );
  }

  if (gameState.phase === 'intro') {
    return (
      <PageWrapper className="bg-[var(--color-parchment)]">
        <div className="page-container cat-copy-page">
          <button
            onClick={() => {
              localStorage.removeItem('cat_session');
              navigate('/games');
            }}
            className="game-back-link"
          >
            ← Back to Games
          </button>

          <div className="cat-intro">
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
              className="text-centered"
            >
              <span className="block text-xs uppercase tracking-[0.2em] text-[var(--color-dust)] mb-3">
                Real-Time Party Game
              </span>
              <div style={{ fontSize: '48px', lineHeight: 1, marginBottom: '12px' }}>🐱</div>
              <h1 className="text-4xl md:text-6xl font-light text-[var(--color-ink)] font-[family-name:var(--font-display)] mb-4">
                cat copy challenge
              </h1>
              <p className="text-centered" style={{ fontSize: '14px', color: 'var(--color-dust)', maxWidth: '448px', margin: '0 auto 48px', lineHeight: '1.7' }}>
                A cat image will flash on screen. Recreate it by drawing or posing, and get voted on by everyone else in real time!
              </p>

              <div className="cat-rules-grid">
                <Card className="text-centered">
                  <div className="text-2xl mb-2">👀</div>
                  <p className="text-[10px] uppercase tracking-widest text-[var(--color-dust)] mb-1">Step 1</p>
                  <p className="text-xs text-[var(--color-ink)]">Memorize the cat</p>
                </Card>
                <Card className="text-centered">
                  <div className="text-2xl mb-2">✏️</div>
                  <p className="text-[10px] uppercase tracking-widest text-[var(--color-dust)] mb-1">Step 2</p>
                  <p className="text-xs text-[var(--color-ink)]">Recreate it</p>
                </Card>
                <Card className="text-centered">
                  <div className="text-2xl mb-2">⭐</div>
                  <p className="text-[10px] uppercase tracking-widest text-[var(--color-dust)] mb-1">Step 3</p>
                  <p className="text-xs text-[var(--color-ink)]">Everyone votes</p>
                </Card>
              </div>

              <div style={{ display: 'flex', justifyContent: 'center', marginTop: '40px' }}>
                <Button variant="primary" onClick={handleJoinLobby}>
                  Let's Go →
                </Button>
              </div>
            </motion.div>
          </div>
        </div>
      </PageWrapper>
    );
  }

  if (gameState.phase === 'lobby') {
    return (
      <PageWrapper className="bg-[var(--color-parchment)]">
        <div className="page-container cat-copy-page">
          <button
            onClick={async () => {
              if (gameId) {
                await supabase
                  .from('cat_players')
                  .delete()
                  .eq('game_id', gameId)
                  .eq('player_name', guestName || '');
              }
              localStorage.removeItem('cat_session');
              navigate('/games');
            }}
            className="game-back-link"
          >
            ← Leave Lobby
          </button>

          <div className="text-centered">
            <span className="block text-xs uppercase tracking-[0.2em] text-[var(--color-dust)] mb-2">
              Waiting Room
            </span>
            <h1 className="text-3xl md:text-5xl font-light text-[var(--color-ink)] font-[family-name:var(--font-display)]">
              Cat Copy Lobby
            </h1>

            <div style={{ maxWidth: '400px', margin: '40px auto 32px' }}>
              <p className="text-xs uppercase tracking-widest text-[var(--color-dust)] mb-4">
                Joined Players ({joinedPlayers.length})
              </p>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                {joinedPlayers.map((player) => {
                  const info = getGuestInfo(player.player_name);
                  const presence = getPlayerPresence(player);
                  return (
                    <Card key={player.player_name} className="flex flex-col items-center p-3 text-centered bg-[var(--color-cream)] relative">
                      <div style={{ position: 'absolute', top: '8px', right: '8px', display: 'flex', alignItems: 'center', gap: '4px', fontSize: '10px' }} title={presence.label}>
                        <span>{presence.emoji}</span>
                      </div>
                      <img src={info.avatar} alt={info.name} style={{ width: '48px', height: '48px', borderRadius: '50%', objectFit: 'cover', marginBottom: '8px' }} />
                      <span className="text-xs uppercase tracking-wider font-semibold text-[var(--color-ink)]">
                        {info.name} {player.is_host && '👑'}
                      </span>
                      {presence.label !== 'connected' && (
                        <span style={{ fontSize: '8px', color: presence.color, textTransform: 'uppercase', fontWeight: 'bold', marginTop: '2px' }}>
                          {presence.label}
                        </span>
                      )}
                    </Card>
                  );
                })}
              </div>
            </div>

            <div style={{ display: 'flex', justifyContent: 'center', marginTop: '32px' }}>
              {isHost ? (
                <Button variant="primary" onClick={handleStart} disabled={joinedPlayers.length < 2}>
                  Start Game ({joinedPlayers.length} players) →
                </Button>
              ) : (
                <div className="text-sm text-[var(--color-dust)]">
                  Waiting for host to start the game...
                </div>
              )}
            </div>
          </div>
        </div>
      </PageWrapper>
    );
  }

  if (showScoreboard || gameState.phase === 'scoreboard') {
    return (
      <PageWrapper className="bg-[var(--color-parchment)]">
        <div className="page-container cat-copy-page">
          <ScoreboardScreen
            votes={allVotesForGame}
            onPlayAgain={handlePlayAgain}
            isHost={isHost}
          />
        </div>
      </PageWrapper>
    );
  }

  // Chaos mode renders full-screen without page wrapper
  if (gameState.phase === 'reveal' && gameState.currentCat) {
    return (
      <CatRevealScreen
        catImage={gameState.currentCat}
        onDone={handleRevealDone}
        duration={gameState.challengeTime}
        roundType={gameState.roundType}
      />
    );
  }

  return (
    <PageWrapper className="bg-[var(--color-parchment)]">
      <div className="page-container cat-copy-page">
        {/* Back button */}
        <button
          onClick={() => {
            localStorage.removeItem('cat_session');
            navigate('/games');
          }}
          className="game-back-link"
        >
          ← Back to Games
        </button>

        <AnimatePresence mode="wait">
          {gameState.phase === 'roulette' && (
            <motion.div key="roulette" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <RouletteScreen
                players={roulettePlayers}
                onSelected={handlePlayerSelected}
                roundType={gameState.roundType}
                round={gameState.round}
              />
            </motion.div>
          )}

          {gameState.phase === 'hold' && (
            <motion.div key="hold" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <HoldScreen
                playerName={gameState.currentPlayer!}
                roundType={gameState.roundType}
                onDone={handleHoldDone}
              />
            </motion.div>
          )}

          {gameState.phase === 'voting' && (
            <motion.div key="voting" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <VotingScreen
                playerName={gameState.currentPlayer!}
                catImage={gameState.currentCat!}
                voters={currentVoters}
                votesList={votesList}
                onSubmitVote={handleVotesSubmitted}
                guestName={guestName || ''}
                joinedPlayers={joinedPlayers}
              />
              <div style={{ display: 'flex', justifyContent: 'center', marginTop: '32px' }}>
                <Button
                  variant="primary"
                  onClick={handleRevealResults}
                  disabled={votesList.length < currentVoters.length}
                >
                  Reveal Results ({votesList.length}/{currentVoters.length} votes) →
                </Button>
              </div>
            </motion.div>
          )}

          {gameState.phase === 'result' && currentRoundResult && (
            <motion.div key="result" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <ResultScreen
                result={currentRoundResult}
                catImage={gameState.currentCat!}
                onNextRound={handleNextRound}
                onEndGame={handleEndGame}
                isLastRound={false}
              />
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </PageWrapper>
  );
}
